# Generated by Django 5.0.3 on 2024-05-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_actor_director_genre_movie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='name',
        ),
    ]
